version: '3.9'

services:
  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - server

  backend:
    image: ${BACKEND_IMAGE}
    container_name: backend
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - DOTNET_RUNNING_IN_CONTAINER=${DOTNET_RUNNING_IN_CONTAINER}
      - DOTNET_USE_POLLING_FILE_WATCHER=${DOTNET_USE_POLLING_FILE_WATCHER}
      - ConnectionStrings__Default=Server=sqlserver,1433;Database=${DB_NAME};User Id=appuser;Password=${APP_USER_PASSWORD};TrustServerCertificate=true;
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_IV=${JWT_IV}
    depends_on:
      - sqlserver
      - keycloak
    networks:
      - server

  sqlserver:
    image: ${SQLSERVER_IMAGE}
    container_name: sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "${SQLSERVER_PORT}:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - server
    deploy:
      resources:
        limits:
          memory: 4g

  sql-init:
    image: ${SQLTOOLS_IMAGE}
    depends_on:
      - sqlserver
    volumes:
      - ./script:/scripts
    entrypoint: /bin/bash -c "sleep 15; /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${SA_PASSWORD} -i /scripts/init.sql"
    networks:
      - server

  postgres_keycloak:
    image: ${POSTGRES_IMAGE}
    container_name: postgres_keycloak
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - server
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=${POSTGRES_PASSWORD} psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1;' >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10

  keycloak:
    image: ${KEYCLOAK_IMAGE}
    container_name: keycloak
    restart: always
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres_keycloak
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    networks:
      - server
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/realms/master || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s  

  admin-service:
    image: ${ADMIN_IMAGE}
    container_name: admin-service
    ports:
      - "${ADMIN_PORT}:3000"
    environment:
      # Base de datos (usando postgres_keycloak ya configurado)
      - DB_HOST=postgres_keycloak
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_TYPE=postgres
      
      # Autenticación de la API (cliente web)
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=master
      - KEYCLOAK_CLIENT_ID=${ADMIN_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${ADMIN_CLIENT_SECRET}
      
      # Operaciones administrativas (cliente admin-cli)
      - KEYCLOAK_ADMIN_USERNAME=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_ADMIN_CLIENT_ID=admin-cli
      
      # Configuración de la aplicación
      - LOG_LEVEL=info
      - PORT=3000
    depends_on:
      - keycloak
      - postgres_keycloak
    networks:
      - server

# PYTHON
  report-service:
    image: ${REPORT_IMAGE}
    container_name: report-service
    restart: always
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=${FLASK_APP}
      - MONGO_URI=${MONGO_URI}      
    ports:
      - "${REPORT_PORT}:5000"
    depends_on:
      - backend
    networks:
      - server  
# BD MONGO
  mongo:
    image: ${MONGO_IMAGE}
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db      
    networks:
      - server
volumes:
  sql_data:
  keycloak_data:
  mongo_data:
networks:
  server:
